{{- with .Values.webServer }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-cm
data:
  INDEX_CONTENT: {{ .indexContent }}
  COLOR: {{ .color }}
{{- end }}
  initScript: |-
{{- include "webworker.initScript" . | indent 4 }}
{{- if .Values.updater.enabled }}
  updaterScript: |-
{{- include "webworker.updaterScript" . | indent 4 }}
{{- end }}
