{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-svc
{{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .exposed }}
  type: LoadBalancer 
{{- else }}
  type: {{ .type }}
{{- end }}
  selector:
    app: {{ $.Release.Name }}-{{ $.Chart.Name }}-webworker
  ports:
    - protocol: TCP
      port: {{ .port | default 80 }}
      targetPort: 80
{{- end }}