{{- if .Values.host_ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-host-ing
  annotations:
    kubernetes.io/ingress.class: nginx
{{- with .Values }}
spec:
  backend:
    serviceName: {{ $.Release.Name }}-default-svc
    servicePort: {{ .default.service.port | default 80 }}
  rules:
    - host: {{ .host_ingress.web_host | default (print $.Release.Name  "-web.local") }}
      http:
        paths:
          - backend:
              serviceName: {{ $.Release.Name }}-web-svc
              servicePort: {{ .web.service.port | default 80 }}
    - host: {{ .host_ingress.worker_host | default (print $.Release.Name "-worker.local") }}
      http:
        paths:
          - backend:
              serviceName: {{ $.Release.Name }}-worker-svc
              servicePort: {{ .worker.service.port | default 80}}
{{- end }}
{{- end }}

--- 

{{- if .Values.path_ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-path-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
{{- with .Values }}
spec:
  backend:
    serviceName: {{ $.Release.Name }}-default-svc
    servicePort: {{ .default.service.port | default 80 }}
  rules:
    - host: {{ .path_ingress.host | default (print $.Release.Name  "-webworker.local") }}
      http:
        paths:
          - path: {{ .path_ingress.web_path | default "/web" }}(/|$)(.*)
            backend:
              serviceName: {{ $.Release.Name }}-web-svc
              servicePort: {{ .web.service.port | default 80 }}
          - path: {{ .path_ingress.web_path | default "/worker" }}(/|$)(.*)
            backend:
              serviceName: {{ $.Release.Name }}-worker-svc
              servicePort: {{ .worker.service.port | default 80 }}
    - http:
        paths:
          - path: /(.*)
            backend:
              serviceName: {{ $.Release.Name }}-default-svc
              servicePort: {{ .default.service.port | default 80 }}
{{- end }}
{{- end }}