{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-svc
spec:
{{- if .exposed }}
  type: LoadBalancer
{{- end }}
  selector:
    app: {{ $.Release.Name }}-{{ $.Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .port }}                 
      targetPort: 80   
{{- end }}