
webServer:
  indexContent: WEB
  color: green
  replicas: 1
  initScript: ""

  labels:
    tier: frontend
  annotations: {}

updater:
  enabled: true
  updaterScript: ""

image:
  repository: nginx
  version: 1.19

service:
  exposed: true
  port: 80
  # if exposed portType=LoadBalancer; if not specify service type
  type: ClusterIP
  annotations: {}