ingress:
  hostEnabled: true
  pathEnabled: true
  pathHost: colors.local

sopot:
  ingressHost: green-webworker.local
  webServer:
    indexContent: sopot
    color: green
    # replicas: 2
    initScript: ""

    labels: 
      tier: frontend
    annotations: {}

  # updater:
  #   enabled: true
  #   updaterScript: ""

  # image:
  #   repository: nginx
  #   version: 1.19

  service:
    exposed: false
    port: 80
    # if exposed portType=LoadBalancer; if not specify service type
    type: ClusterIP
    annotations: {}
    

torun:
  ingressHost: red-webworker.local
  webServer:
    indexContent: torun
    color: red
    # replicas: 2
    initScript: ""

    labels:
      tier: frontend
    annotations: {}

  # updater:
  #   enabled: true
  #   updaterScript: ""

  # image:
  #   repository: nginx
  #   version: 1.19

  service:
    exposed: false
    port: 80
    # if exposed portType=LoadBalancer; if not specify service type
    type: ClusterIP
    annotations: {}

default:
  webServer:
    indexContent: sorry
    color: yellow
  updater:
    enabled: false
  service:
    exposed: false